### ISSUE TITLE
parse_nk.py does not support BERT

### ISSUE THREAD

**Issue by sopankhosla** [pariajm/joint-disfluency-detection-and-parsing#1]
I was not able to run the given scripts with BERT model. It seems like the parse_nk.py does not support BERT models yet. Please let me know if that is the case and would the repo be updated?

**Comment by pariajm** [comment]
I updated the repo. It should work fine now.

**Comment by pariajm** [comment]
> I was not able to run the given scripts with BERT model. It seems like the parse_nk.py does not support BERT models yet. Please let me know if that is the case and would the repo be updated?

I updated the repo. It should work fine now.
